fix: `yamllint` issues
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

diff --git a/policygenerator/policy-sets/stable/openshift-plus/input-quay/policy-config-quay.yaml b/policygenerator/policy-sets/stable/openshift-plus/input-quay/policy-config-quay.yaml
--- a/policygenerator/policy-sets/stable/openshift-plus/input-quay/policy-config-quay.yaml
+++ b/policygenerator/policy-sets/stable/openshift-plus/input-quay/policy-config-quay.yaml
@@ -27,136 +27,136 @@ spec:
   template:
     spec:
       containers:
-      - command:
-        - /bin/bash
-        - -c
-        - |
-          #!/usr/bin/env bash
+        - command:
+            - /bin/bash
+            - -c
+            - |
+              #!/usr/bin/env bash
 
-          function quay_cmd() {
-            DATA='{}'
-            if [ ! -z "$4" ]; then
-              DATA=$4
-            fi
-            echo "[$1] $2 $3 --data $DATA" 1>&2
-            AUTH="Fake: dummy"
-            if [ $1 = "Basic" ]; then
-              COUNT=$(oc -n $QUAY_NAMESPACE get --ignore-not-found=true secret $QUAY_USER_SECRET | wc -l)
-              if [ $COUNT -gt 1 ]; then
-                  BASIC=$(oc -n $QUAY_NAMESPACE extract secret/$QUAY_USER_SECRET --keys=basic --to=-)
+              function quay_cmd() {
+                DATA='{}'
+                if [ ! -z "$4" ]; then
+                  DATA=$4
+                fi
+                echo "[$1] $2 $3 --data $DATA" 1>&2
+                AUTH="Fake: dummy"
+                if [ $1 = "Basic" ]; then
+                  COUNT=$(oc -n $QUAY_NAMESPACE get --ignore-not-found=true secret $QUAY_USER_SECRET | wc -l)
+                  if [ $COUNT -gt 1 ]; then
+                      BASIC=$(oc -n $QUAY_NAMESPACE extract secret/$QUAY_USER_SECRET --keys=basic --to=-)
+                  fi
+                  AUTH="Authorization: Basic $BASIC"
+
+                elif [ $1 = "Bearer" ]; then
+                  AUTH="Authorization: Bearer $TOKEN"
+                fi
+                curl -X $2 $CURL_OPTS -H 'Content-Type: application/json'  -H "$AUTH" https://$QUAY_HOST$3 --data "$DATA"
+                echo "[INFO] Success" 1>&2
+              }
+              echo -n "Waiting for the Quay Registry CR to be available ."
+              RC=$(oc wait QuayRegistry -n local-quay registry --for=condition=Available=true > /dev/null 2>&1;echo $?)
+
+              while [ $RC -ne 0 ]; do
+                sleep 2
+                echo -n "."
+                RC=$(oc wait QuayRegistry -n local-quay registry --for=condition=Available=true > /dev/null 2>&1;echo $?)
+              done
+              echo "done"
+
+              CURL_OPTS="-fsk"
+              QUAY_ADMIN=quayadmin
+              QUAY_USER=quaydevel
+              QUAY_USER_SECRET=$QUAY_USER
+              QUAY_NAMESPACE=local-quay
+              QUAY_HOST=$(oc get route -n $QUAY_NAMESPACE registry-quay -o jsonpath='{.spec.host}')
+              QUAY_ORG=devel
+              QUAY_ORG_EMAIL=devel@myorg.com
+              QUAY_REPO=example
+              if [ $? -ne 0 ]; then
+                echo "Quay route does not exist yet, please wait and try again."
+                exit 1
               fi
-              AUTH="Authorization: Basic $BASIC"
+              RESULT=$(oc get secret -n $QUAY_NAMESPACE $QUAY_USER_SECRET)
+              if [ $? -eq 0 ]; then
+                echo "Quay user configuration secret already exists: $QUAY_USER_SECRET in namespace $QUAY_NAMESPACE"
+                exit 1
+              fi
 
-            elif [ $1 = "Bearer" ]; then
-              AUTH="Authorization: Bearer $TOKEN"
-            fi
-            curl -X $2 $CURL_OPTS -H 'Content-Type: application/json'  -H "$AUTH" https://$QUAY_HOST$3 --data "$DATA"
-            echo "[INFO] Success" 1>&2
-          }
-          echo -n "Waiting for the Quay Registry CR to be available ."
-          RC=$(oc wait QuayRegistry -n local-quay registry --for=condition=Available=true > /dev/null 2>&1;echo $?)
+              ADMINPASS=`head -c 8 /dev/urandom | base64 | sed 's/=//'`
+              BASE64AUTH=`echo -n $QUAY_USER:$QUAY_PASSWORD | base64 -w0`
+              RESULT=$(curl -X POST -k -s https://$QUAY_HOST/api/v1/user/initialize --header 'Content-Type: application/json' --data "{ \"username\": \"quayadmin\", \"password\":\"${ADMINPASS}\", \"email\": \"quayadmin@example.com\", \"access_token\": true}")
+              echo "$RESULT" | grep -q "non-empty database"
+              if [ $? -eq 0 ]; then
+                echo "Quay user configuration failed, the database has been initialized."
+                exit 1
+              else
+                echo "[INFO] Destroy any previous secrets ..."
+                oc -n $QUAY_NAMESPACE delete --ignore-not-found=true secret $QUAY_USER_SECRET
 
-          while [ $RC -ne 0 ]; do
-            sleep 2
-            echo -n "."
-            RC=$(oc wait QuayRegistry -n local-quay registry --for=condition=Available=true > /dev/null 2>&1;echo $?)
-          done
-          echo "done"
+                echo "[INFO] Creating quay admin secret quayadmin ..."
+                TOKEN=$(echo "$RESULT" | tr ',' '\n' | grep access_token | awk -F: '{print $2}' | sed 's/"//g')
+                oc -n $QUAY_NAMESPACE create secret generic quayadmin --from-literal=token=$TOKEN --from-literal=password=$ADMINPASS --from-literal=basic="$BASE64AUTH"
 
-          CURL_OPTS="-fsk"
-          QUAY_ADMIN=quayadmin
-          QUAY_USER=quaydevel
-          QUAY_USER_SECRET=$QUAY_USER
-          QUAY_NAMESPACE=local-quay
-          QUAY_HOST=$(oc get route -n $QUAY_NAMESPACE registry-quay -o jsonpath='{.spec.host}')
-          QUAY_ORG=devel
-          QUAY_ORG_EMAIL=devel@myorg.com
-          QUAY_REPO=example
-          if [ $? -ne 0 ]; then
-            echo "Quay route does not exist yet, please wait and try again."
-            exit 1
-          fi
-          RESULT=$(oc get secret -n $QUAY_NAMESPACE $QUAY_USER_SECRET)
-          if [ $? -eq 0 ]; then
-            echo "Quay user configuration secret already exists: $QUAY_USER_SECRET in namespace $QUAY_NAMESPACE"
-            exit 1
-          fi
+                echo "[INFO] Creating $QUAY_USER user ..."
+                RESPONSE=$(quay_cmd Bearer POST /api/v1/superuser/users/ "{ \"username\": \"$QUAY_USER\", \"email\": \"$QUAY_USER_EMAIL\", \"access_token\": true}")
 
-          ADMINPASS=`head -c 8 /dev/urandom | base64 | sed 's/=//'`
-          BASE64AUTH=`echo -n $QUAY_USER:$QUAY_PASSWORD | base64 -w0`
-          RESULT=$(curl -X POST -k -s https://$QUAY_HOST/api/v1/user/initialize --header 'Content-Type: application/json' --data "{ \"username\": \"quayadmin\", \"password\":\"${ADMINPASS}\", \"email\": \"quayadmin@example.com\", \"access_token\": true}")
-          echo "$RESULT" | grep -q "non-empty database"
-          if [ $? -eq 0 ]; then
-            echo "Quay user configuration failed, the database has been initialized."
-            exit 1
-          else
-            echo "[INFO] Destroy any previous secrets ..."
-            oc -n $QUAY_NAMESPACE delete --ignore-not-found=true secret $QUAY_USER_SECRET
+                QUAY_PASSWORD=$(echo $RESPONSE | tr ',' '\n' | grep '"password"' | cut -d \" -f 4)
+                BASE64AUTH=`echo -n $QUAY_USER:$QUAY_PASSWORD | base64 -w0`
 
-            echo "[INFO] Creating quay admin secret quayadmin ..."
-            TOKEN=$(echo "$RESULT" | tr ',' '\n' | grep access_token | awk -F: '{print $2}' | sed 's/"//g')
-            oc -n $QUAY_NAMESPACE create secret generic quayadmin --from-literal=token=$TOKEN --from-literal=password=$ADMINPASS --from-literal=basic="$BASE64AUTH"
+                echo "[INFO] Creating $QUAY_USER_SECRET secret ..."
+                oc -n $QUAY_NAMESPACE create secret generic $QUAY_USER_SECRET --from-literal=password="$QUAY_PASSWORD" --from-literal=basic="$BASE64AUTH"
 
-            echo "[INFO] Creating $QUAY_USER user ..."
-            RESPONSE=$(quay_cmd Bearer POST /api/v1/superuser/users/ "{ \"username\": \"$QUAY_USER\", \"email\": \"$QUAY_USER_EMAIL\", \"access_token\": true}")
+                echo "[INFO] Creating quay-pull-secret ..."
+                echo -e "{ \"auths\": { \"$QUAY_HOST\": { \"auth\": \"$BASE64AUTH\" } }}" | oc -n $QUAY_NAMESPACE create secret generic quay-pull-secret --from-file=.dockerconfigjson=/dev/stdin --type=kubernetes.io/dockerconfigjson
 
-            QUAY_PASSWORD=$(echo $RESPONSE | tr ',' '\n' | grep '"password"' | cut -d \" -f 4)
-            BASE64AUTH=`echo -n $QUAY_USER:$QUAY_PASSWORD | base64 -w0`
+                echo "[INFO] Creating quay integration token secret ..."
+                oc -n $QUAY_NAMESPACE create secret generic quay-integration --from-literal=token=$TOKEN
+              fi
 
-            echo "[INFO] Creating $QUAY_USER_SECRET secret ..."
-            oc -n $QUAY_NAMESPACE create secret generic $QUAY_USER_SECRET --from-literal=password="$QUAY_PASSWORD" --from-literal=basic="$BASE64AUTH"
+              echo "[INFO] Looking for initial organization ..."
+              COUNT=$(quay_cmd Bearer GET /api/v1/organization/$QUAY_ORG | grep -v not_found | wc -l)
+              if [ $COUNT = 0 ]; then
+                echo "[INFO] Creating $QUAY_ORG org ..."
+                # Email cannot be shared with the initial user
+                quay_cmd Bearer POST /api/v1/organization/ "{\"name\": \"$QUAY_ORG\", \"email\": \"$QUAY_ORG_EMAIL\" }"
+                quay_cmd Basic GET /api/v1/organization/$QUAY_ORG
+              fi
 
-            echo "[INFO] Creating quay-pull-secret ..."
-            echo -e "{ \"auths\": { \"$QUAY_HOST\": { \"auth\": \"$BASE64AUTH\" } }}" | oc -n $QUAY_NAMESPACE create secret generic quay-pull-secret --from-file=.dockerconfigjson=/dev/stdin --type=kubernetes.io/dockerconfigjson
+              echo "[INFO] Looking for org application ..."
+              # The only way to get another OAuth token is to go to: Organization -> Applications -> {app} -> Generate Token
+              # If there was a programatic way to do it here, we could avoid the problem with the bearer token expiring after 150min
+              APPLICATION=automation
+              COUNT=$(quay_cmd Bearer GET /api/v1/organization/$QUAY_ORG/applications | grep $APPLICATION | wc -l)
+              if [ $COUNT = 0 ]; then
+                echo "[INFO] Creating $APPLICATION application..."
+                quay_cmd Bearer POST /api/v1/organization/$QUAY_ORG/applications "{\"name\": \"$QUAY_ORG-automation\", \"description\": \"automation app\" }"
+              fi
 
-            echo "[INFO] Creating quay integration token secret ..."
-            oc -n $QUAY_NAMESPACE create secret generic quay-integration --from-literal=token=$TOKEN
-          fi
+              echo "[INFO] Looking for initial repo ..."
+              COUNT=$(quay_cmd Bearer GET /api/v1/repository/$QUAY_ORG/$QUAY_REPO | grep -v not_found | wc -l)
+              if [ $COUNT = 0 ]; then
+                echo "[INFO] Creating $QUAY_REPO repo..."
+                quay_cmd Bearer POST /api/v1/repository "{\"namespace\":\"$QUAY_ORG\", \"repository\":\"$QUAY_REPO\", \"visibility\":\"public\", \"description\":\"Development Repo\", \"repo_kind\":\"image\"}"
+              fi
 
-          echo "[INFO] Looking for initial organization ..."
-          COUNT=$(quay_cmd Bearer GET /api/v1/organization/$QUAY_ORG | grep -v not_found | wc -l)
-          if [ $COUNT = 0 ]; then
-            echo "[INFO] Creating $QUAY_ORG org ..."
-            # Email cannot be shared with the initial user
-            quay_cmd Bearer POST /api/v1/organization/ "{\"name\": \"$QUAY_ORG\", \"email\": \"$QUAY_ORG_EMAIL\" }"
-            quay_cmd Basic GET /api/v1/organization/$QUAY_ORG
-          fi
+              echo "[INFO] Looking for $QUAY_ORG members ..."
+              COUNT=$(quay_cmd Bearer GET /api/v1/organization/$QUAY_ORG/team/owners/members | grep "name\": \"$QUAY_USER\"" | wc -l)
+              if [ $COUNT = 0 ]; then
+                echo "[INFO] Associating $QUAY_USER with $QUAY_ORG ..."
+                quay_cmd Bearer PUT /api/v1/organization/$QUAY_ORG/team/owners/members/$QUAY_USER '{}'
+              fi
 
-          echo "[INFO] Looking for org application ..."
-          # The only way to get another OAuth token is to go to: Organization -> Applications -> {app} -> Generate Token
-          # If there was a programatic way to do it here, we could avoid the problem with the bearer token expiring after 150min
-          APPLICATION=automation
-          COUNT=$(quay_cmd Bearer GET /api/v1/organization/$QUAY_ORG/applications | grep $APPLICATION | wc -l)
-          if [ $COUNT = 0 ]; then
-            echo "[INFO] Creating $APPLICATION application..."
-            quay_cmd Bearer POST /api/v1/organization/$QUAY_ORG/applications "{\"name\": \"$QUAY_ORG-automation\", \"description\": \"automation app\" }"
-          fi
+              echo "[INFO] Looking for $QUAY_REPO admins ..."
+              COUNT=$(quay_cmd Bearer GET /api/v1/repository/$QUAY_ORG/$QUAY_REPO/permissions/user/$QUAY_USER | grep '"role": "admin"' | wc -l)
+              if [ $COUNT = 0 ]; then
+                echo "[INFO] Give $QUAY_USER admin rights to the repo ..."
+                quay_cmd Bearer PUT /api/v1/repository/$QUAY_ORG/$QUAY_REPO/permissions/user/$QUAY_USER '{ "role": "admin"}'
+              fi
 
-          echo "[INFO] Looking for initial repo ..."
-          COUNT=$(quay_cmd Bearer GET /api/v1/repository/$QUAY_ORG/$QUAY_REPO | grep -v not_found | wc -l)
-          if [ $COUNT = 0 ]; then
-            echo "[INFO] Creating $QUAY_REPO repo..."
-            quay_cmd Bearer POST /api/v1/repository "{\"namespace\":\"$QUAY_ORG\", \"repository\":\"$QUAY_REPO\", \"visibility\":\"public\", \"description\":\"Development Repo\", \"repo_kind\":\"image\"}"
-          fi
-
-          echo "[INFO] Looking for $QUAY_ORG members ..."
-          COUNT=$(quay_cmd Bearer GET /api/v1/organization/$QUAY_ORG/team/owners/members | grep "name\": \"$QUAY_USER\"" | wc -l)
-          if [ $COUNT = 0 ]; then
-            echo "[INFO] Associating $QUAY_USER with $QUAY_ORG ..."
-            quay_cmd Bearer PUT /api/v1/organization/$QUAY_ORG/team/owners/members/$QUAY_USER '{}'
-          fi
-
-          echo "[INFO] Looking for $QUAY_REPO admins ..."
-          COUNT=$(quay_cmd Bearer GET /api/v1/repository/$QUAY_ORG/$QUAY_REPO/permissions/user/$QUAY_USER | grep '"role": "admin"' | wc -l)
-          if [ $COUNT = 0 ]; then
-            echo "[INFO] Give $QUAY_USER admin rights to the repo ..."
-            quay_cmd Bearer PUT /api/v1/repository/$QUAY_ORG/$QUAY_REPO/permissions/user/$QUAY_USER '{ "role": "admin"}'
-          fi
-
-          echo "[INFO] Job finished"
-        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
-        imagePullPolicy: Always
-        name: create-admin-user
+              echo "[INFO] Job finished"
+          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
+          imagePullPolicy: Always
+          name: create-admin-user
       dnsPolicy: ClusterFirst
       restartPolicy: Never
       serviceAccount: create-admin-user
